/*
 * DevHub API Platform
 * DevHub API provides a structured set of developer-oriented services designed to simplify common backend tasks and accelerate application development.  The platform is organized into functional domains, each delivering reliable and production-ready utilities.  ### 📄 Document & Data Processing - Markdown → HTML conversion - Markdown → PDF rendering (custom themes supported) - CSV → JSON conversion - JSON → XML conversion - and more..  Designed for automation pipelines, CMS integrations and content-driven applications.  ### 🛠 Utilities - UUID generation - Random password generation - Minify CSS - Minify JS  Lightweight, fast and suitable for system-level integration.  ### 🔐 Security & Data Protection - Data sanitization - Data validation  Designed to enforce data integrity, prevent common security threats, and ensure safe handling of user input across applications.  ### 🚧 Upcoming Services Additional modules currently under development, including notification services and external integrations.  ### Platform Features - JWT Authentication (Bearer Token) - Per-endpoint rate limiting - Consistent validation and predictable error handling - Secure-by-default design  The API surface will expand progressively while maintaining backward compatibility.  **Maintained and designed by <a href=\"mailto:info@giuseppecocchiara.it\">Giuseppe Cocchiara</a>, founder of DevHub project**
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.devhubapi.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Standard request to log-in and receive Bearer token
 */
@JsonPropertyOrder({
  AuthRequest.JSON_PROPERTY_USERNAME,
  AuthRequest.JSON_PROPERTY_PASSWORD
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-04-13T00:38:16.902282200+02:00[Europe/Rome]", comments = "Generator version: 7.19.0")
public class AuthRequest {
  public static final String JSON_PROPERTY_USERNAME = "username";
  @jakarta.annotation.Nullable
  private String username;

  public static final String JSON_PROPERTY_PASSWORD = "password";
  @jakarta.annotation.Nullable
  private String password;

  public AuthRequest() {
  }

  public AuthRequest username(@jakarta.annotation.Nullable String username) {
    
    this.username = username;
    return this;
  }

  /**
   * Username credential
   * @return username
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_USERNAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getUsername() {
    return username;
  }


  @JsonProperty(value = JSON_PROPERTY_USERNAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUsername(@jakarta.annotation.Nullable String username) {
    this.username = username;
  }

  public AuthRequest password(@jakarta.annotation.Nullable String password) {
    
    this.password = password;
    return this;
  }

  /**
   * Password credential
   * @return password
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PASSWORD, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPassword() {
    return password;
  }


  @JsonProperty(value = JSON_PROPERTY_PASSWORD, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPassword(@jakarta.annotation.Nullable String password) {
    this.password = password;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AuthRequest authRequest = (AuthRequest) o;
    return Objects.equals(this.username, authRequest.username) &&
        Objects.equals(this.password, authRequest.password);
  }

  @Override
  public int hashCode() {
    return Objects.hash(username, password);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AuthRequest {\n");
    sb.append("    username: ").append(toIndentedString(username)).append("\n");
    sb.append("    password: ").append(toIndentedString(password)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

