/*
 * DevHub API Platform
 * DevHub API provides a structured set of developer-oriented services designed to simplify common backend tasks and accelerate application development.  The platform is organized into functional domains, each delivering reliable and production-ready utilities.  ### 📄 Document & Data Processing - Markdown → HTML conversion - Markdown → PDF rendering (custom themes supported) - CSV → JSON conversion - JSON → XML conversion - and more..  Designed for automation pipelines, CMS integrations and content-driven applications.  ### 🛠 Utilities - UUID generation - Random password generation - Minify CSS - Minify JS  Lightweight, fast and suitable for system-level integration.  ### 🔐 Security & Data Protection - Data sanitization - Data validation  Designed to enforce data integrity, prevent common security threats, and ensure safe handling of user input across applications.  ### 🚧 Upcoming Services Additional modules currently under development, including notification services and external integrations.  ### Platform Features - JWT Authentication (Bearer Token) - Per-endpoint rate limiting - Consistent validation and predictable error handling - Secure-by-default design  The API surface will expand progressively while maintaining backward compatibility.  **Maintained and designed by <a href=\"mailto:info@giuseppecocchiara.it\">Giuseppe Cocchiara</a>, founder of DevHub project**
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.devhubapi.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Standard error response for DevHub APIs
 */
@JsonPropertyOrder({
  DevHubErrorResponse.JSON_PROPERTY_ERROR,
  DevHubErrorResponse.JSON_PROPERTY_STATUS,
  DevHubErrorResponse.JSON_PROPERTY_PATH,
  DevHubErrorResponse.JSON_PROPERTY_REQUEST_ID,
  DevHubErrorResponse.JSON_PROPERTY_SUPPORT_CODE,
  DevHubErrorResponse.JSON_PROPERTY_TIMESTAMP
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-04-13T00:38:16.902282200+02:00[Europe/Rome]", comments = "Generator version: 7.19.0")
public class DevHubErrorResponse {
  public static final String JSON_PROPERTY_ERROR = "error";
  @jakarta.annotation.Nullable
  private String error;

  public static final String JSON_PROPERTY_STATUS = "status";
  @jakarta.annotation.Nullable
  private Integer status;

  public static final String JSON_PROPERTY_PATH = "path";
  @jakarta.annotation.Nullable
  private String path;

  public static final String JSON_PROPERTY_REQUEST_ID = "requestId";
  @jakarta.annotation.Nullable
  private String requestId;

  public static final String JSON_PROPERTY_SUPPORT_CODE = "supportCode";
  @jakarta.annotation.Nullable
  private String supportCode;

  public static final String JSON_PROPERTY_TIMESTAMP = "timestamp";
  @jakarta.annotation.Nullable
  private String timestamp;

  public DevHubErrorResponse() {
  }

  public DevHubErrorResponse error(@jakarta.annotation.Nullable String error) {
    
    this.error = error;
    return this;
  }

  /**
   * Human-readable error message
   * @return error
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ERROR, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getError() {
    return error;
  }


  @JsonProperty(value = JSON_PROPERTY_ERROR, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setError(@jakarta.annotation.Nullable String error) {
    this.error = error;
  }

  public DevHubErrorResponse status(@jakarta.annotation.Nullable Integer status) {
    
    this.status = status;
    return this;
  }

  /**
   * HTTP status code
   * @return status
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_STATUS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getStatus() {
    return status;
  }


  @JsonProperty(value = JSON_PROPERTY_STATUS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStatus(@jakarta.annotation.Nullable Integer status) {
    this.status = status;
  }

  public DevHubErrorResponse path(@jakarta.annotation.Nullable String path) {
    
    this.path = path;
    return this;
  }

  /**
   * API path that generated the error
   * @return path
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PATH, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPath() {
    return path;
  }


  @JsonProperty(value = JSON_PROPERTY_PATH, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPath(@jakarta.annotation.Nullable String path) {
    this.path = path;
  }

  public DevHubErrorResponse requestId(@jakarta.annotation.Nullable String requestId) {
    
    this.requestId = requestId;
    return this;
  }

  /**
   * Unique request identifier for log correlation
   * @return requestId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_REQUEST_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getRequestId() {
    return requestId;
  }


  @JsonProperty(value = JSON_PROPERTY_REQUEST_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRequestId(@jakarta.annotation.Nullable String requestId) {
    this.requestId = requestId;
  }

  public DevHubErrorResponse supportCode(@jakarta.annotation.Nullable String supportCode) {
    
    this.supportCode = supportCode;
    return this;
  }

  /**
   * Support error code used for troubleshooting and documentation
   * @return supportCode
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SUPPORT_CODE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSupportCode() {
    return supportCode;
  }


  @JsonProperty(value = JSON_PROPERTY_SUPPORT_CODE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSupportCode(@jakarta.annotation.Nullable String supportCode) {
    this.supportCode = supportCode;
  }

  public DevHubErrorResponse timestamp(@jakarta.annotation.Nullable String timestamp) {
    
    this.timestamp = timestamp;
    return this;
  }

  /**
   * Timestamp of the error occurrence
   * @return timestamp
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TIMESTAMP, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTimestamp() {
    return timestamp;
  }


  @JsonProperty(value = JSON_PROPERTY_TIMESTAMP, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTimestamp(@jakarta.annotation.Nullable String timestamp) {
    this.timestamp = timestamp;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DevHubErrorResponse devHubErrorResponse = (DevHubErrorResponse) o;
    return Objects.equals(this.error, devHubErrorResponse.error) &&
        Objects.equals(this.status, devHubErrorResponse.status) &&
        Objects.equals(this.path, devHubErrorResponse.path) &&
        Objects.equals(this.requestId, devHubErrorResponse.requestId) &&
        Objects.equals(this.supportCode, devHubErrorResponse.supportCode) &&
        Objects.equals(this.timestamp, devHubErrorResponse.timestamp);
  }

  @Override
  public int hashCode() {
    return Objects.hash(error, status, path, requestId, supportCode, timestamp);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DevHubErrorResponse {\n");
    sb.append("    error: ").append(toIndentedString(error)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    path: ").append(toIndentedString(path)).append("\n");
    sb.append("    requestId: ").append(toIndentedString(requestId)).append("\n");
    sb.append("    supportCode: ").append(toIndentedString(supportCode)).append("\n");
    sb.append("    timestamp: ").append(toIndentedString(timestamp)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

