/*
 * DevHub API Platform
 * DevHub API provides a structured set of developer-oriented services designed to simplify common backend tasks and accelerate application development.  The platform is organized into functional domains, each delivering reliable and production-ready utilities.  ### 📄 Document & Data Processing - Markdown → HTML conversion - Markdown → PDF rendering (custom themes supported) - CSV → JSON conversion - JSON → XML conversion - and more..  Designed for automation pipelines, CMS integrations and content-driven applications.  ### 🛠 Utilities - UUID generation - Random password generation - Minify CSS - Minify JS  Lightweight, fast and suitable for system-level integration.  ### 🔐 Security & Data Protection - Data sanitization - Data validation  Designed to enforce data integrity, prevent common security threats, and ensure safe handling of user input across applications.  ### 🚧 Upcoming Services Additional modules currently under development, including notification services and external integrations.  ### Platform Features - JWT Authentication (Bearer Token) - Per-endpoint rate limiting - Consistent validation and predictable error handling - Secure-by-default design  The API surface will expand progressively while maintaining backward compatibility.  **Maintained and designed by <a href=\"mailto:info@giuseppecocchiara.it\">Giuseppe Cocchiara</a>, founder of DevHub project**
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.devhubapi.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Request body for generating custom random passwords
 */
@JsonPropertyOrder({
  PasswordRequest.JSON_PROPERTY_LENGTH,
  PasswordRequest.JSON_PROPERTY_STRENGTH,
  PasswordRequest.JSON_PROPERTY_INCLUDE_LETTERS,
  PasswordRequest.JSON_PROPERTY_INCLUDE_NUMBERS,
  PasswordRequest.JSON_PROPERTY_INCLUDE_SPECIALS,
  PasswordRequest.JSON_PROPERTY_EXCLUDED_SPECIALS
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-04-13T00:38:16.902282200+02:00[Europe/Rome]", comments = "Generator version: 7.19.0")
public class PasswordRequest {
  public static final String JSON_PROPERTY_LENGTH = "length";
  @jakarta.annotation.Nullable
  private Integer length;

  public static final String JSON_PROPERTY_STRENGTH = "strength";
  @jakarta.annotation.Nullable
  private String strength;

  public static final String JSON_PROPERTY_INCLUDE_LETTERS = "includeLetters";
  @jakarta.annotation.Nullable
  private Boolean includeLetters;

  public static final String JSON_PROPERTY_INCLUDE_NUMBERS = "includeNumbers";
  @jakarta.annotation.Nullable
  private Boolean includeNumbers;

  public static final String JSON_PROPERTY_INCLUDE_SPECIALS = "includeSpecials";
  @jakarta.annotation.Nullable
  private Boolean includeSpecials;

  public static final String JSON_PROPERTY_EXCLUDED_SPECIALS = "excludedSpecials";
  @jakarta.annotation.Nullable
  private String excludedSpecials;

  public PasswordRequest() {
  }

  public PasswordRequest length(@jakarta.annotation.Nullable Integer length) {
    
    this.length = length;
    return this;
  }

  /**
   * Get length
   * @return length
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_LENGTH, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getLength() {
    return length;
  }


  @JsonProperty(value = JSON_PROPERTY_LENGTH, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLength(@jakarta.annotation.Nullable Integer length) {
    this.length = length;
  }

  public PasswordRequest strength(@jakarta.annotation.Nullable String strength) {
    
    this.strength = strength;
    return this;
  }

  /**
   * Get strength
   * @return strength
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_STRENGTH, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getStrength() {
    return strength;
  }


  @JsonProperty(value = JSON_PROPERTY_STRENGTH, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStrength(@jakarta.annotation.Nullable String strength) {
    this.strength = strength;
  }

  public PasswordRequest includeLetters(@jakarta.annotation.Nullable Boolean includeLetters) {
    
    this.includeLetters = includeLetters;
    return this;
  }

  /**
   * Get includeLetters
   * @return includeLetters
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_INCLUDE_LETTERS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getIncludeLetters() {
    return includeLetters;
  }


  @JsonProperty(value = JSON_PROPERTY_INCLUDE_LETTERS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIncludeLetters(@jakarta.annotation.Nullable Boolean includeLetters) {
    this.includeLetters = includeLetters;
  }

  public PasswordRequest includeNumbers(@jakarta.annotation.Nullable Boolean includeNumbers) {
    
    this.includeNumbers = includeNumbers;
    return this;
  }

  /**
   * Get includeNumbers
   * @return includeNumbers
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_INCLUDE_NUMBERS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getIncludeNumbers() {
    return includeNumbers;
  }


  @JsonProperty(value = JSON_PROPERTY_INCLUDE_NUMBERS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIncludeNumbers(@jakarta.annotation.Nullable Boolean includeNumbers) {
    this.includeNumbers = includeNumbers;
  }

  public PasswordRequest includeSpecials(@jakarta.annotation.Nullable Boolean includeSpecials) {
    
    this.includeSpecials = includeSpecials;
    return this;
  }

  /**
   * Get includeSpecials
   * @return includeSpecials
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_INCLUDE_SPECIALS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getIncludeSpecials() {
    return includeSpecials;
  }


  @JsonProperty(value = JSON_PROPERTY_INCLUDE_SPECIALS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIncludeSpecials(@jakarta.annotation.Nullable Boolean includeSpecials) {
    this.includeSpecials = includeSpecials;
  }

  public PasswordRequest excludedSpecials(@jakarta.annotation.Nullable String excludedSpecials) {
    
    this.excludedSpecials = excludedSpecials;
    return this;
  }

  /**
   * Get excludedSpecials
   * @return excludedSpecials
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_EXCLUDED_SPECIALS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getExcludedSpecials() {
    return excludedSpecials;
  }


  @JsonProperty(value = JSON_PROPERTY_EXCLUDED_SPECIALS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setExcludedSpecials(@jakarta.annotation.Nullable String excludedSpecials) {
    this.excludedSpecials = excludedSpecials;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PasswordRequest passwordRequest = (PasswordRequest) o;
    return Objects.equals(this.length, passwordRequest.length) &&
        Objects.equals(this.strength, passwordRequest.strength) &&
        Objects.equals(this.includeLetters, passwordRequest.includeLetters) &&
        Objects.equals(this.includeNumbers, passwordRequest.includeNumbers) &&
        Objects.equals(this.includeSpecials, passwordRequest.includeSpecials) &&
        Objects.equals(this.excludedSpecials, passwordRequest.excludedSpecials);
  }

  @Override
  public int hashCode() {
    return Objects.hash(length, strength, includeLetters, includeNumbers, includeSpecials, excludedSpecials);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PasswordRequest {\n");
    sb.append("    length: ").append(toIndentedString(length)).append("\n");
    sb.append("    strength: ").append(toIndentedString(strength)).append("\n");
    sb.append("    includeLetters: ").append(toIndentedString(includeLetters)).append("\n");
    sb.append("    includeNumbers: ").append(toIndentedString(includeNumbers)).append("\n");
    sb.append("    includeSpecials: ").append(toIndentedString(includeSpecials)).append("\n");
    sb.append("    excludedSpecials: ").append(toIndentedString(excludedSpecials)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

