/*
 * DevHub API Platform
 * DevHub API provides a structured set of developer-oriented services designed to simplify common backend tasks and accelerate application development.  The platform is organized into functional domains, each delivering reliable and production-ready utilities.  ### 📄 Document & Data Processing - Markdown → HTML conversion - Markdown → PDF rendering (custom themes supported) - CSV → JSON conversion - JSON → XML conversion - and more..  Designed for automation pipelines, CMS integrations and content-driven applications.  ### 🛠 Utilities - UUID generation - Random password generation - Minify CSS - Minify JS  Lightweight, fast and suitable for system-level integration.  ### 🔐 Security & Data Protection - Data sanitization - Data validation  Designed to enforce data integrity, prevent common security threats, and ensure safe handling of user input across applications.  ### 🚧 Upcoming Services Additional modules currently under development, including notification services and external integrations.  ### Platform Features - JWT Authentication (Bearer Token) - Per-endpoint rate limiting - Consistent validation and predictable error handling - Secure-by-default design  The API surface will expand progressively while maintaining backward compatibility.  **Maintained and designed by <a href=\"mailto:info@giuseppecocchiara.it\">Giuseppe Cocchiara</a>, founder of DevHub project**
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.devhubapi.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * SanitizationResult
 */
@JsonPropertyOrder({
  SanitizationResult.JSON_PROPERTY_SANITIZED,
  SanitizationResult.JSON_PROPERTY_CONTEXT_APPLIED,
  SanitizationResult.JSON_PROPERTY_ISSUES_DETECTED,
  SanitizationResult.JSON_PROPERTY_ACTIONS_APPLIED,
  SanitizationResult.JSON_PROPERTY_RISK_LEVEL,
  SanitizationResult.JSON_PROPERTY_RISK_SCORE,
  SanitizationResult.JSON_PROPERTY_EXPLANATIONS
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-04-13T00:38:16.902282200+02:00[Europe/Rome]", comments = "Generator version: 7.19.0")
public class SanitizationResult {
  public static final String JSON_PROPERTY_SANITIZED = "sanitized";
  @jakarta.annotation.Nullable
  private String sanitized;

  /**
   * Gets or Sets contextApplied
   */
  public enum ContextAppliedEnum {
    HTML(String.valueOf("HTML")),
    
    JSON(String.valueOf("JSON")),
    
    CSV(String.valueOf("CSV")),
    
    LOG(String.valueOf("LOG"));

    private String value;

    ContextAppliedEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static ContextAppliedEnum fromValue(String value) {
      for (ContextAppliedEnum b : ContextAppliedEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_CONTEXT_APPLIED = "contextApplied";
  @jakarta.annotation.Nullable
  private ContextAppliedEnum contextApplied;

  public static final String JSON_PROPERTY_ISSUES_DETECTED = "issuesDetected";
  @jakarta.annotation.Nullable
  private List<String> issuesDetected = new ArrayList<>();

  public static final String JSON_PROPERTY_ACTIONS_APPLIED = "actionsApplied";
  @jakarta.annotation.Nullable
  private List<String> actionsApplied = new ArrayList<>();

  public static final String JSON_PROPERTY_RISK_LEVEL = "riskLevel";
  @jakarta.annotation.Nullable
  private String riskLevel;

  public static final String JSON_PROPERTY_RISK_SCORE = "riskScore";
  @jakarta.annotation.Nullable
  private Integer riskScore;

  public static final String JSON_PROPERTY_EXPLANATIONS = "explanations";
  @jakarta.annotation.Nullable
  private List<String> explanations = new ArrayList<>();

  public SanitizationResult() {
  }

  public SanitizationResult sanitized(@jakarta.annotation.Nullable String sanitized) {
    
    this.sanitized = sanitized;
    return this;
  }

  /**
   * Get sanitized
   * @return sanitized
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SANITIZED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSanitized() {
    return sanitized;
  }


  @JsonProperty(value = JSON_PROPERTY_SANITIZED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSanitized(@jakarta.annotation.Nullable String sanitized) {
    this.sanitized = sanitized;
  }

  public SanitizationResult contextApplied(@jakarta.annotation.Nullable ContextAppliedEnum contextApplied) {
    
    this.contextApplied = contextApplied;
    return this;
  }

  /**
   * Get contextApplied
   * @return contextApplied
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CONTEXT_APPLIED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ContextAppliedEnum getContextApplied() {
    return contextApplied;
  }


  @JsonProperty(value = JSON_PROPERTY_CONTEXT_APPLIED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setContextApplied(@jakarta.annotation.Nullable ContextAppliedEnum contextApplied) {
    this.contextApplied = contextApplied;
  }

  public SanitizationResult issuesDetected(@jakarta.annotation.Nullable List<String> issuesDetected) {
    
    this.issuesDetected = issuesDetected;
    return this;
  }

  public SanitizationResult addIssuesDetectedItem(String issuesDetectedItem) {
    if (this.issuesDetected == null) {
      this.issuesDetected = new ArrayList<>();
    }
    this.issuesDetected.add(issuesDetectedItem);
    return this;
  }

  /**
   * Get issuesDetected
   * @return issuesDetected
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ISSUES_DETECTED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getIssuesDetected() {
    return issuesDetected;
  }


  @JsonProperty(value = JSON_PROPERTY_ISSUES_DETECTED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIssuesDetected(@jakarta.annotation.Nullable List<String> issuesDetected) {
    this.issuesDetected = issuesDetected;
  }

  public SanitizationResult actionsApplied(@jakarta.annotation.Nullable List<String> actionsApplied) {
    
    this.actionsApplied = actionsApplied;
    return this;
  }

  public SanitizationResult addActionsAppliedItem(String actionsAppliedItem) {
    if (this.actionsApplied == null) {
      this.actionsApplied = new ArrayList<>();
    }
    this.actionsApplied.add(actionsAppliedItem);
    return this;
  }

  /**
   * Get actionsApplied
   * @return actionsApplied
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ACTIONS_APPLIED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getActionsApplied() {
    return actionsApplied;
  }


  @JsonProperty(value = JSON_PROPERTY_ACTIONS_APPLIED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setActionsApplied(@jakarta.annotation.Nullable List<String> actionsApplied) {
    this.actionsApplied = actionsApplied;
  }

  public SanitizationResult riskLevel(@jakarta.annotation.Nullable String riskLevel) {
    
    this.riskLevel = riskLevel;
    return this;
  }

  /**
   * Get riskLevel
   * @return riskLevel
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_RISK_LEVEL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getRiskLevel() {
    return riskLevel;
  }


  @JsonProperty(value = JSON_PROPERTY_RISK_LEVEL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRiskLevel(@jakarta.annotation.Nullable String riskLevel) {
    this.riskLevel = riskLevel;
  }

  public SanitizationResult riskScore(@jakarta.annotation.Nullable Integer riskScore) {
    
    this.riskScore = riskScore;
    return this;
  }

  /**
   * Get riskScore
   * @return riskScore
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_RISK_SCORE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getRiskScore() {
    return riskScore;
  }


  @JsonProperty(value = JSON_PROPERTY_RISK_SCORE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRiskScore(@jakarta.annotation.Nullable Integer riskScore) {
    this.riskScore = riskScore;
  }

  public SanitizationResult explanations(@jakarta.annotation.Nullable List<String> explanations) {
    
    this.explanations = explanations;
    return this;
  }

  public SanitizationResult addExplanationsItem(String explanationsItem) {
    if (this.explanations == null) {
      this.explanations = new ArrayList<>();
    }
    this.explanations.add(explanationsItem);
    return this;
  }

  /**
   * Get explanations
   * @return explanations
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_EXPLANATIONS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getExplanations() {
    return explanations;
  }


  @JsonProperty(value = JSON_PROPERTY_EXPLANATIONS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setExplanations(@jakarta.annotation.Nullable List<String> explanations) {
    this.explanations = explanations;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SanitizationResult sanitizationResult = (SanitizationResult) o;
    return Objects.equals(this.sanitized, sanitizationResult.sanitized) &&
        Objects.equals(this.contextApplied, sanitizationResult.contextApplied) &&
        Objects.equals(this.issuesDetected, sanitizationResult.issuesDetected) &&
        Objects.equals(this.actionsApplied, sanitizationResult.actionsApplied) &&
        Objects.equals(this.riskLevel, sanitizationResult.riskLevel) &&
        Objects.equals(this.riskScore, sanitizationResult.riskScore) &&
        Objects.equals(this.explanations, sanitizationResult.explanations);
  }

  @Override
  public int hashCode() {
    return Objects.hash(sanitized, contextApplied, issuesDetected, actionsApplied, riskLevel, riskScore, explanations);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SanitizationResult {\n");
    sb.append("    sanitized: ").append(toIndentedString(sanitized)).append("\n");
    sb.append("    contextApplied: ").append(toIndentedString(contextApplied)).append("\n");
    sb.append("    issuesDetected: ").append(toIndentedString(issuesDetected)).append("\n");
    sb.append("    actionsApplied: ").append(toIndentedString(actionsApplied)).append("\n");
    sb.append("    riskLevel: ").append(toIndentedString(riskLevel)).append("\n");
    sb.append("    riskScore: ").append(toIndentedString(riskScore)).append("\n");
    sb.append("    explanations: ").append(toIndentedString(explanations)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

