/*
 * DevHub API Platform
 * DevHub API provides a structured set of developer-oriented services designed to simplify common backend tasks and accelerate application development.  The platform is organized into functional domains, each delivering reliable and production-ready utilities.  ### 📄 Document & Data Processing - Markdown → HTML conversion - Markdown → PDF rendering (custom themes supported) - CSV → JSON conversion - JSON → XML conversion - and more..  Designed for automation pipelines, CMS integrations and content-driven applications.  ### 🛠 Utilities - UUID generation - Random password generation - Minify CSS - Minify JS  Lightweight, fast and suitable for system-level integration.  ### 🔐 Security & Data Protection - Data sanitization - Data validation  Designed to enforce data integrity, prevent common security threats, and ensure safe handling of user input across applications.  ### 🚧 Upcoming Services Additional modules currently under development, including notification services and external integrations.  ### Platform Features - JWT Authentication (Bearer Token) - Per-endpoint rate limiting - Consistent validation and predictable error handling - Secure-by-default design  The API surface will expand progressively while maintaining backward compatibility.  **Maintained and designed by <a href=\"mailto:info@giuseppecocchiara.it\">Giuseppe Cocchiara</a>, founder of DevHub project**
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.devhubapi.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * SanitizationRequest
 */
@JsonPropertyOrder({
  SanitizationRequest.JSON_PROPERTY_INPUT,
  SanitizationRequest.JSON_PROPERTY_CONTEXT,
  SanitizationRequest.JSON_PROPERTY_MODE,
  SanitizationRequest.JSON_PROPERTY_OPERATIONS
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-04-13T00:38:16.902282200+02:00[Europe/Rome]", comments = "Generator version: 7.19.0")
public class SanitizationRequest {
  public static final String JSON_PROPERTY_INPUT = "input";
  @jakarta.annotation.Nullable
  private String input;

  public static final String JSON_PROPERTY_CONTEXT = "context";
  @jakarta.annotation.Nullable
  private String context;

  public static final String JSON_PROPERTY_MODE = "mode";
  @jakarta.annotation.Nullable
  private String mode;

  /**
   * Gets or Sets operations
   */
  public enum OperationsEnum {
    NONE(String.valueOf("NONE")),
    
    NORMALIZE_WHITESPACE(String.valueOf("NORMALIZE_WHITESPACE")),
    
    LOWERCASE(String.valueOf("LOWERCASE")),
    
    REMOVE_ACCENTS(String.valueOf("REMOVE_ACCENTS")),
    
    REMOVE_PII(String.valueOf("REMOVE_PII"));

    private String value;

    OperationsEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static OperationsEnum fromValue(String value) {
      for (OperationsEnum b : OperationsEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_OPERATIONS = "operations";
  @jakarta.annotation.Nullable
  private List<OperationsEnum> operations = new ArrayList<>();

  public SanitizationRequest() {
  }

  public SanitizationRequest input(@jakarta.annotation.Nullable String input) {
    
    this.input = input;
    return this;
  }

  /**
   * Get input
   * @return input
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_INPUT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getInput() {
    return input;
  }


  @JsonProperty(value = JSON_PROPERTY_INPUT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setInput(@jakarta.annotation.Nullable String input) {
    this.input = input;
  }

  public SanitizationRequest context(@jakarta.annotation.Nullable String context) {
    
    this.context = context;
    return this;
  }

  /**
   * Get context
   * @return context
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CONTEXT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getContext() {
    return context;
  }


  @JsonProperty(value = JSON_PROPERTY_CONTEXT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setContext(@jakarta.annotation.Nullable String context) {
    this.context = context;
  }

  public SanitizationRequest mode(@jakarta.annotation.Nullable String mode) {
    
    this.mode = mode;
    return this;
  }

  /**
   * Get mode
   * @return mode
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_MODE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getMode() {
    return mode;
  }


  @JsonProperty(value = JSON_PROPERTY_MODE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMode(@jakarta.annotation.Nullable String mode) {
    this.mode = mode;
  }

  public SanitizationRequest operations(@jakarta.annotation.Nullable List<OperationsEnum> operations) {
    
    this.operations = operations;
    return this;
  }

  public SanitizationRequest addOperationsItem(OperationsEnum operationsItem) {
    if (this.operations == null) {
      this.operations = new ArrayList<>();
    }
    this.operations.add(operationsItem);
    return this;
  }

  /**
   * Get operations
   * @return operations
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_OPERATIONS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<OperationsEnum> getOperations() {
    return operations;
  }


  @JsonProperty(value = JSON_PROPERTY_OPERATIONS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOperations(@jakarta.annotation.Nullable List<OperationsEnum> operations) {
    this.operations = operations;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SanitizationRequest sanitizationRequest = (SanitizationRequest) o;
    return Objects.equals(this.input, sanitizationRequest.input) &&
        Objects.equals(this.context, sanitizationRequest.context) &&
        Objects.equals(this.mode, sanitizationRequest.mode) &&
        Objects.equals(this.operations, sanitizationRequest.operations);
  }

  @Override
  public int hashCode() {
    return Objects.hash(input, context, mode, operations);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SanitizationRequest {\n");
    sb.append("    input: ").append(toIndentedString(input)).append("\n");
    sb.append("    context: ").append(toIndentedString(context)).append("\n");
    sb.append("    mode: ").append(toIndentedString(mode)).append("\n");
    sb.append("    operations: ").append(toIndentedString(operations)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

