/*
 * DevHub API Platform
 * DevHub API provides a structured set of developer-oriented services designed to simplify common backend tasks and accelerate application development.  The platform is organized into functional domains, each delivering reliable and production-ready utilities.  ### 📄 Document & Data Processing - Markdown → HTML conversion - Markdown → PDF rendering (custom themes supported) - CSV → JSON conversion - JSON → XML conversion - and more..  Designed for automation pipelines, CMS integrations and content-driven applications.  ### 🛠 Utilities - UUID generation - Random password generation - Minify CSS - Minify JS  Lightweight, fast and suitable for system-level integration.  ### 🔐 Security & Data Protection - Data sanitization - Data validation  Designed to enforce data integrity, prevent common security threats, and ensure safe handling of user input across applications.  ### 🚧 Upcoming Services Additional modules currently under development, including notification services and external integrations.  ### Platform Features - JWT Authentication (Bearer Token) - Per-endpoint rate limiting - Consistent validation and predictable error handling - Secure-by-default design  The API surface will expand progressively while maintaining backward compatibility.  **Maintained and designed by <a href=\"mailto:info@giuseppecocchiara.it\">Giuseppe Cocchiara</a>, founder of DevHub project**
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.devhubapi.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * ValidateRequest
 */
@JsonPropertyOrder({
  ValidateRequest.JSON_PROPERTY_INPUT,
  ValidateRequest.JSON_PROPERTY_RULES,
  ValidateRequest.JSON_PROPERTY_FAIL_FAST
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-04-13T00:38:16.902282200+02:00[Europe/Rome]", comments = "Generator version: 7.19.0")
public class ValidateRequest {
  public static final String JSON_PROPERTY_INPUT = "input";
  @jakarta.annotation.Nullable
  private String input;

  public static final String JSON_PROPERTY_RULES = "rules";
  @jakarta.annotation.Nullable
  private List<String> rules = new ArrayList<>();

  public static final String JSON_PROPERTY_FAIL_FAST = "failFast";
  @jakarta.annotation.Nullable
  private Boolean failFast;

  public ValidateRequest() {
  }

  public ValidateRequest input(@jakarta.annotation.Nullable String input) {
    
    this.input = input;
    return this;
  }

  /**
   * Get input
   * @return input
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_INPUT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getInput() {
    return input;
  }


  @JsonProperty(value = JSON_PROPERTY_INPUT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setInput(@jakarta.annotation.Nullable String input) {
    this.input = input;
  }

  public ValidateRequest rules(@jakarta.annotation.Nullable List<String> rules) {
    
    this.rules = rules;
    return this;
  }

  public ValidateRequest addRulesItem(String rulesItem) {
    if (this.rules == null) {
      this.rules = new ArrayList<>();
    }
    this.rules.add(rulesItem);
    return this;
  }

  /**
   * Get rules
   * @return rules
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_RULES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getRules() {
    return rules;
  }


  @JsonProperty(value = JSON_PROPERTY_RULES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRules(@jakarta.annotation.Nullable List<String> rules) {
    this.rules = rules;
  }

  public ValidateRequest failFast(@jakarta.annotation.Nullable Boolean failFast) {
    
    this.failFast = failFast;
    return this;
  }

  /**
   * Get failFast
   * @return failFast
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_FAIL_FAST, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getFailFast() {
    return failFast;
  }


  @JsonProperty(value = JSON_PROPERTY_FAIL_FAST, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFailFast(@jakarta.annotation.Nullable Boolean failFast) {
    this.failFast = failFast;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ValidateRequest validateRequest = (ValidateRequest) o;
    return Objects.equals(this.input, validateRequest.input) &&
        Objects.equals(this.rules, validateRequest.rules) &&
        Objects.equals(this.failFast, validateRequest.failFast);
  }

  @Override
  public int hashCode() {
    return Objects.hash(input, rules, failFast);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ValidateRequest {\n");
    sb.append("    input: ").append(toIndentedString(input)).append("\n");
    sb.append("    rules: ").append(toIndentedString(rules)).append("\n");
    sb.append("    failFast: ").append(toIndentedString(failFast)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

