/*
 * DevHub API Platform
 * DevHub API provides a structured set of developer-oriented services designed to simplify common backend tasks and accelerate application development.  The platform is organized into functional domains, each delivering reliable and production-ready utilities.  ### 📄 Document & Data Processing - Markdown → HTML conversion - Markdown → PDF rendering (custom themes supported) - CSV → JSON conversion - JSON → XML conversion - and more..  Designed for automation pipelines, CMS integrations and content-driven applications.  ### 🛠 Utilities - UUID generation - Random password generation - Minify CSS - Minify JS  Lightweight, fast and suitable for system-level integration.  ### 🔐 Security & Data Protection - Data sanitization - Data validation  Designed to enforce data integrity, prevent common security threats, and ensure safe handling of user input across applications.  ### 🚧 Upcoming Services Additional modules currently under development, including notification services and external integrations.  ### Platform Features - JWT Authentication (Bearer Token) - Per-endpoint rate limiting - Consistent validation and predictable error handling - Secure-by-default design  The API surface will expand progressively while maintaining backward compatibility.  **Maintained and designed by <a href=\"mailto:info@giuseppecocchiara.it\">Giuseppe Cocchiara</a>, founder of DevHub project**
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.devhubapi.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.devhubapi.sdk.model.ValidationError;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * ValidateResponse
 */
@JsonPropertyOrder({
  ValidateResponse.JSON_PROPERTY_VALID,
  ValidateResponse.JSON_PROPERTY_ERRORS
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-04-13T00:38:16.902282200+02:00[Europe/Rome]", comments = "Generator version: 7.19.0")
public class ValidateResponse {
  public static final String JSON_PROPERTY_VALID = "valid";
  @jakarta.annotation.Nullable
  private Boolean valid;

  public static final String JSON_PROPERTY_ERRORS = "errors";
  @jakarta.annotation.Nullable
  private List<ValidationError> errors = new ArrayList<>();

  public ValidateResponse() {
  }

  public ValidateResponse valid(@jakarta.annotation.Nullable Boolean valid) {
    
    this.valid = valid;
    return this;
  }

  /**
   * Get valid
   * @return valid
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_VALID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getValid() {
    return valid;
  }


  @JsonProperty(value = JSON_PROPERTY_VALID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setValid(@jakarta.annotation.Nullable Boolean valid) {
    this.valid = valid;
  }

  public ValidateResponse errors(@jakarta.annotation.Nullable List<ValidationError> errors) {
    
    this.errors = errors;
    return this;
  }

  public ValidateResponse addErrorsItem(ValidationError errorsItem) {
    if (this.errors == null) {
      this.errors = new ArrayList<>();
    }
    this.errors.add(errorsItem);
    return this;
  }

  /**
   * Get errors
   * @return errors
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ERRORS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<ValidationError> getErrors() {
    return errors;
  }


  @JsonProperty(value = JSON_PROPERTY_ERRORS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setErrors(@jakarta.annotation.Nullable List<ValidationError> errors) {
    this.errors = errors;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ValidateResponse validateResponse = (ValidateResponse) o;
    return Objects.equals(this.valid, validateResponse.valid) &&
        Objects.equals(this.errors, validateResponse.errors);
  }

  @Override
  public int hashCode() {
    return Objects.hash(valid, errors);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ValidateResponse {\n");
    sb.append("    valid: ").append(toIndentedString(valid)).append("\n");
    sb.append("    errors: ").append(toIndentedString(errors)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

