/*
 * DevHub API Platform
 * DevHub API provides a structured set of developer-oriented services designed to simplify common backend tasks and accelerate application development.  The platform is organized into functional domains, each delivering reliable and production-ready utilities.  ### 📄 Document & Data Processing - Markdown → HTML conversion - Markdown → PDF rendering (custom themes supported) - CSV → JSON conversion - JSON → XML conversion - and more..  Designed for automation pipelines, CMS integrations and content-driven applications.  ### 🛠 Utilities - UUID generation - Random password generation - Minify CSS - Minify JS  Lightweight, fast and suitable for system-level integration.  ### 🔐 Security & Data Protection - Data sanitization - Data validation  Designed to enforce data integrity, prevent common security threats, and ensure safe handling of user input across applications.  ### 🚧 Upcoming Services Additional modules currently under development, including notification services and external integrations.  ### Platform Features - JWT Authentication (Bearer Token) - Per-endpoint rate limiting - Consistent validation and predictable error handling - Secure-by-default design  The API surface will expand progressively while maintaining backward compatibility.  **Maintained and designed by <a href=\"mailto:info@giuseppecocchiara.it\">Giuseppe Cocchiara</a>, founder of DevHub project**
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.devhubapi.sdk.api;

import com.devhubapi.sdk.model.AuthRequest;
import com.devhubapi.sdk.model.AuthResponse;
import com.devhubapi.sdk.model.DevHubErrorResponse;
import com.devhubapi.sdk.model.RefreshTokenRequest;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

/**
 * API tests for LoginApi
 */
@Disabled
public class LoginApiTest {

    private final LoginApi api = new LoginApi();

    
    /**
     * The service authenticates the API Client by username and password
     *
     * It returns the Bearer token in case of valid credentials, unauthorized (401) otherwise
     */
    @Test
    public void loginTest()  {
        // uncomment below to test the function
        //AuthRequest authRequest = null;
        //AuthResponse response = api.login(authRequest).block();

        // TODO: test validations
    }
    
    /**
     * Refresh JWT access token using a valid refresh token
     *
     * Returns a new access token and optionally a new refresh token
     */
    @Test
    public void refreshTokenTest()  {
        // uncomment below to test the function
        //RefreshTokenRequest refreshTokenRequest = null;
        //AuthResponse response = api.refreshToken(refreshTokenRequest).block();

        // TODO: test validations
    }
    
}
