/*
 * DevHub API Platform
 * DevHub API provides a structured set of developer-oriented services designed to simplify common backend tasks and accelerate application development.  The platform is organized into functional domains, each delivering reliable and production-ready utilities.  ### 📄 Document & Data Processing - Markdown → HTML conversion - Markdown → PDF rendering (custom themes supported) - CSV → JSON conversion - JSON → XML conversion - and more..  Designed for automation pipelines, CMS integrations and content-driven applications.  ### 🛠 Utilities - UUID generation - Random password generation - Minify CSS - Minify JS  Lightweight, fast and suitable for system-level integration.  ### 🔐 Security & Data Protection - Data sanitization - Data validation  Designed to enforce data integrity, prevent common security threats, and ensure safe handling of user input across applications.  ### 🚧 Upcoming Services Additional modules currently under development, including notification services and external integrations.  ### Platform Features - JWT Authentication (Bearer Token) - Per-endpoint rate limiting - Consistent validation and predictable error handling - Secure-by-default design  The API surface will expand progressively while maintaining backward compatibility.  **Maintained and designed by <a href=\"mailto:info@giuseppecocchiara.it\">Giuseppe Cocchiara</a>, founder of DevHub project**
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.devhubapi.sdk;

import java.time.Instant;
import java.time.OffsetDateTime;
import java.time.ZonedDateTime;

import com.fasterxml.jackson.databind.module.SimpleModule;
import com.fasterxml.jackson.databind.Module.SetupContext;

@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-04-13T00:38:16.902282200+02:00[Europe/Rome]", comments = "Generator version: 7.19.0")
public class RFC3339JavaTimeModule extends SimpleModule {
    private static final long serialVersionUID = 1L;

    public RFC3339JavaTimeModule() {
        super("RFC3339JavaTimeModule");
    }

   @Override
   public void setupModule(SetupContext context) {
       super.setupModule(context);

       addDeserializer(Instant.class, RFC3339InstantDeserializer.INSTANT);
       addDeserializer(OffsetDateTime.class, RFC3339InstantDeserializer.OFFSET_DATE_TIME);
       addDeserializer(ZonedDateTime.class, RFC3339InstantDeserializer.ZONED_DATE_TIME);
   }

}
